### PR TITLE
Multistage dockerfile

### PR DESCRIPTION
**Pull request by gnoam**
Ref. #5 
`Containerfile` changed to use multistage build with alpine images.

/kind feature

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
cc @leonardpahlke

**Comment by RinkiyaKeDad** [comment]
/cc @leonardpahlke @encodeflush 

pinging for another look :)

**Comment by leonardpahlke** [comment]
Thank you @gnoam! 
/lgtm

**Review by encodeflush — COMMENTED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/approve

**Comment by cpanato** [comment]
thanks!

**Pull request merged**
