### PR TITLE
Update owners

### PR DESCRIPTION
**Pull request by leonardpahlke**
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

I added the tool creators to the reviewers. (see https://github.com/encodeflush/testgrid-json-exporter)

### CODE REVIEW

**Comment by leonardpahlke** [comment]
@justaugustus @saschagrunert this PR updates the reviewers (OWNERS) with the tool authors, since @encodeflush and I are not part of the organization yet, should I close this PR again, or should I apply for membership?

**Comment by cpanato** [comment]
I would say apply for membership

**Review by saschagrunert — APPROVED** [review]
Yep :+1:

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
